name: SonarQube

on:
  push:
    branches:
      - main
      - relese
      - develop
  pull_request:
    branches:
      - main
      - release
      - develop

env:
  SLN_NAME: TestSonarCloud
  DOTNET_VERSION: '6.0'
  GITHUB_TOKEN: ${{secrets.GITHUBTOKEN}}
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
            node-version: '14'   
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - uses: microsoft/setup-msbuild@v1
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Restore NuGet packages
        run: nuget restore 'TestSonarCloud.sln'
      - name: Begin Sonar scan
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /o:gamatron7devops /k:gamatron7devops_TestSonarCloud /d:sonar.cs.opencover.reportsPaths=TestProject/coverage.opencover.xml /d:sonar.coverage.exclusions="**Test*.cs,**/Models/*,**StartUp.cs" /d:sonar.exclusions="**/Scripts/*" /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io
          dotnet restore
          dotnet build
      - name: Test
        run : dotnet test TestProject/TestProject.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: End Sonar scan
        run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
