name: SonarQube

on:
  push:
    branches:
      - main
      - relese
      - develop
  pull_request:
    branches:
      - main
      - release
      - develop
env:
  SLN_NAME: TestSonarCloud

jobs:
  sonarQubeTrigger:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name : restore        
        run :  dotnet restore
      - name : build
        run :  dotnet build
      - name: Sonarscanner for dotnet
        uses: Secbyte/dotnet-sonarscanner@v2.3
        with:
          buildCommand: dotnet build .
          #testCommand: dotnet test ${{ env.SLN_NAME }}.test/${{ env.SLN_NAME }}.test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          projectKey: gamatron7devops_TestSonarCloud
          projectName: ${{ github.event.repository.name }}
          sonarOrganisation: gamatron7devops
          beginArguments: >
              /d:sonar.cs.opencover.reportsPaths='${{ env.SLN_NAME }}.test/coverage.opencover.xml' 
              /d:sonar.coverage.exclusions="**Test*.cs,**/Models/*"
              /d:sonar.exclusions="**/Scripts/*"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
